#!/usr/bin/env bash
set -eu

readonly SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
readonly EXTENSION_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
readonly LOG_FILE="${JUNIE_NOTIFICATIONS_LOG:-${HOME}/notifications.log}"
readonly HOOKS_FILE="${JUNIE_HOOKS_FILE:-$EXTENSION_DIR/.hooks-enabled}"
readonly LOGO_SOURCE="$EXTENSION_DIR/resources/junie-logo.svg"

readonly WINDOWS_POWERSHELL_APP_ID='Microsoft.AutoGenerated.{BD8B063D-B0C1-C893-293E-DB7643CF143F}'

VERBOSE=false
INPUT=''

log() {
    printf '%s pid=%s %s\n' \
        "$(date '+%Y-%m-%dT%H:%M:%S%z')" \
        "$$" \
        "$*" >>"$LOG_FILE" 2>/dev/null || true
}

debug() {
    [ "$VERBOSE" = true ] || return 0
    printf '%s\n' "$*"
}

parse_arguments() {
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --verbose)
                VERBOSE=true
                ;;
            test|-)
                ;;
            *)
                [ -n "$INPUT" ] || INPUT="$1"
                ;;
        esac
        shift
    done
}

read_input() {
    if [ -z "$INPUT" ]; then
        INPUT="$(cat)"
    fi
}

json_event() {
    printf '%s' "$INPUT" |
        python3 -c '
import json
import sys

data = json.load(sys.stdin)
print(data.get("hook_event_name", "Junie"))
' 2>/dev/null || true
}

json_message() {
    printf '%s' "$INPUT" |
        python3 -c '
import json
import sys

data = json.load(sys.stdin)

message = (
    data.get("last_assistant_message")
    or data.get("reason")
    or data.get("prompt")
    or data.get("tool_name")
    or "Junie activity"
)

print(message.replace("\n", " ")[:240])
' 2>/dev/null || true
}

event_enabled() {
    local event="$1"
    local hook
    local value

    [ -f "$HOOKS_FILE" ] || return 1

    while IFS='=' read -r hook value; do
        hook="${hook%%#*}"
        value="${value%%#*}"

        hook="${hook//[[:space:]]/}"
        value="${value//[[:space:]]/}"

        if [ "$hook" = "$event" ] && [ "$value" = true ]; then
            return 0
        fi
    done < "$HOOKS_FILE"

    return 1
}

base64_utf8() {
    printf '%s' "$1" | base64 -w0
}

windows_logo_path() {
    if [ -f "$LOGO_SOURCE" ] && command -v wslpath >/dev/null 2>&1; then
        wslpath -w "$LOGO_SOURCE"
    fi
}

build_powershell_command() {
    local title="$1"
    local message="$2"
    local logo_source="$3"

    local title_base64
    local message_base64
    local logo_source_base64

    title_base64="$(base64_utf8 "$title")"
    message_base64="$(base64_utf8 "$message")"
    logo_source_base64="$(base64_utf8 "$logo_source")"

    cat <<PS
\$ErrorActionPreference = 'Stop'

\$encoding = [System.Text.Encoding]::UTF8

\$title = \$encoding.GetString([Convert]::FromBase64String('$title_base64'))
\$body = \$encoding.GetString([Convert]::FromBase64String('$message_base64'))
\$logoSource = \$encoding.GetString([Convert]::FromBase64String('$logo_source_base64'))

\$title = [System.Security.SecurityElement]::Escape(\$title)
\$body = [System.Security.SecurityElement]::Escape(\$body)

\$logo = ''

if (\$logoSource -and (Test-Path -LiteralPath \$logoSource)) {
    \$logoDirectory = Join-Path \$env:TEMP 'junie'

    New-Item -ItemType Directory -Force -Path \$logoDirectory | Out-Null

    \$logoDestination = Join-Path \$logoDirectory 'junie-logo.svg'

    Copy-Item -LiteralPath \$logoSource -Destination \$logoDestination -Force

    \$logoUri = [Uri]::new(\$logoDestination).AbsoluteUri
    \$logo = "<image placement='appLogoOverride' src='\$logoUri'/>"
}

[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
[Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime] | Out-Null

\$xml = New-Object Windows.Data.Xml.Dom.XmlDocument

\$xml.LoadXml("<toast><visual><binding template='ToastGeneric'>\$logo<text>\$title</text><text>\$body</text></binding></visual></toast>")

\$toast = New-Object Windows.UI.Notifications.ToastNotification \$xml

[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('$WINDOWS_POWERSHELL_APP_ID').Show(\$toast)
PS
}

send_windows_toast() {
    local title="$1"
    local message="$2"

    command -v powershell.exe >/dev/null 2>&1 || return 1

    local logo_source
    local powershell_command
    local output

    logo_source="$(windows_logo_path || true)"
    powershell_command="$(build_powershell_command "$title" "$message" "$logo_source")"

    if [ "$VERBOSE" = true ]; then
        printf '%s\n' '--- Junie notification debug ---'
        printf 'Input JSON: %s\n' "$INPUT"
        printf 'Event: %s\n' "$EVENT"
        printf 'Title: %s\n' "$title"
        printf 'Body: %s\n' "$message"
        printf 'Logo source: %s\n' "$logo_source"
        printf 'AppID: %s\n' "$WINDOWS_POWERSHELL_APP_ID"
        printf '%s\n' 'PowerShell command:'
        printf '%s\n' "$powershell_command"
    fi

    if output="$(
        powershell.exe \
            -NoProfile \
            -NonInteractive \
            -ExecutionPolicy Bypass \
            -Command "$powershell_command" \
            2>&1
    )"; then
        debug 'Windows toast sent successfully.'

        if [ "$VERBOSE" = true ] && [ -n "$output" ]; then
            printf '%s\n' "$output"
        fi

        debug '--- end debug ---'
        return 0
    fi

    printf '%s\n' 'Windows toast delivery failed.' >&2

    if [ "$VERBOSE" = true ] && [ -n "$output" ]; then
        printf '%s\n' 'PowerShell error:' >&2
        printf '%s\n' "$output" >&2
    fi

    return 1
}

send_fallback_notification() {
    local title="$1"
    local message="$2"

    if command -v notify-send >/dev/null 2>&1; then
        notify-send "$title" "$message" 2>/dev/null || true
        return 0
    fi

    printf '%s: %s\n' "$title" "$message"
}

send_notification() {
    local title="$1"
    local message="$2"

    if [ -n "${JUNIE_NOTIFY_COMMAND:-}" ]; then
        "$JUNIE_NOTIFY_COMMAND" "$title" "$message"
        return 0
    fi

    if send_windows_toast "$title" "$message"; then
        return 0
    fi

    send_fallback_notification "$title" "$message"
}

parse_arguments "$@"
read_input

log "invoked args=$*"
log "received payload_bytes=${#INPUT}"

EVENT="$(json_event)"
EVENT="${EVENT:-Junie}"

if ! event_enabled "$EVENT"; then
    log "event=$EVENT disabled"
    exit 0
fi

MESSAGE="$(json_message)"
MESSAGE="${MESSAGE:-Junie activity}"

TITLE="Junie - $EVENT"

log "event=$EVENT message=$MESSAGE"

send_notification "$TITLE" "$MESSAGE"

log "notification processing completed event=$EVENT"
